### ISSUE TITLE
feedback_value is wrong sometimes?

### ISSUE THREAD

**Issue by AUDIOX-CD** [slerpxcq/openuac2_fw#1]
void USBD_AUDIO_UpdateFB(USBD_HandleTypeDef *pdev)
//   int64_t tmp = (haudio->aud_buf.size - (haudio->aud_buf.capacity >> 1)) << 3;	
int64_t tmp = ((int32_t)haudio->aud_buf.size - ((int32_t)haudio->aud_buf.capacity >> 1)) << 3;  //this is changed code

**Comment by slerpxcq** [comment]
Thanks, will fix.
